ElJournal/Controllers/ProfItemsController.cs
using ElJournal.Filter;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ElJournal.Controllers
{
    [Authorize, Log]
    public class ProfItemsController : Controller
    {
        private ElJournalContext context = new ElJournalContext();
        // GET: ProfItems
        public ActionResult Index()
        {
            var user = context.ProfessorsItem.Include(u => u.Professor).Include(u => u.Item);
            return View(user.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.ProfessorId = new SelectList(context.Professor, "Id", "F");
            ViewBag.ItemId = new SelectList(context.NameItem, "Id", "NameItem1");
            return View();
        }

        public ActionResult ErrorPage()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ProfessorId,ItemId")] ProfessorsItem user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    context.ProfessorsItem.Add(user);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.ProfessorId = new SelectList(context.Professor, "Id", "F", user.ProfessorId);
                ViewBag.ItemId = new SelectList(context.NameItem, "Id", "NameItem1", user.ItemId);
                return View(user);
            }
            catch (System.Exception)
            {
                return Redirect("~/Professor/ErrorPage");
            }


        }

        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                ProfessorsItem user = context.ProfessorsItem.Find(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ProfessorId = new SelectList(context.Professor, "Id", "F", user.ProfessorId);
                ViewBag.ItemId = new SelectList(context.NameItem, "Id", "NameItem1", user.ItemId);
                return View(user);
            }
            catch (System.Exception)
            {
                return Redirect("~/Professor/ErrorPage");
            }
          
        }

        // POST: Users/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ProfessorId,ItemId")] ProfessorsItem user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    context.Entry(user).State = EntityState.Modified;
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ProfessorId = new SelectList(context.Professor, "Id", "F", user.ProfessorId);
                ViewBag.ItemId = new SelectList(context.NameItem, "Id", "NameItem1", user.ItemId);
                return View(user);
            }
            catch (System.Exception)
            {
                return Redirect("~/Professor/ErrorPage");
            }
          
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProfessorsItem user = context.ProfessorsItem.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProfessorsItem user = context.ProfessorsItem.Find(id);
            context.ProfessorsItem.Remove(user);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElJournal/Controllers/ProfessorController.cs
using ElJournal.Filter;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ElJournal.Controllers
{
    [Authorize, Log]
    public class ProfessorController : Controller
    {
        // GET: Professor
        private ElJournalContext context = new ElJournalContext();
        public async Task<ActionResult> Index(string searchString, ElJournalContext context1)
        {
            var searchSpace = from m in context1.Professor
                              select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                searchSpace = searchSpace.Where(s => s.F.Contains(searchString) || s.I.Contains(searchString));
            }
            return View(await searchSpace.ToListAsync());
        }

        public ActionResult NewProfItems()
        {
            return Redirect("~/ProfItems/Index");
        }

        // GET: Evaluation/Create
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                return Redirect("~/Professor/ErrorPage");
            }
           
        }

        public ActionResult ErrorPage()
        {
            return View();
        }

        // POST: NameItem/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,F,I,O")] Professor nameItem)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    context.Professor.Add(nameItem);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(nameItem);
            }
            catch (Exception)
            {
                return Redirect("~/Professor/ErrorPage");
            }
        
        }

        // GET: NameItem/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Professor nameItem = context.Professor.Find(id);
                if (nameItem == null)
                {
                    return HttpNotFound();
                }
                return View(nameItem);
            }
            catch (Exception)
            {
                return Redirect("~/Professor/ErrorPage"); 
            }
           
        }

        // POST: NameItem/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,F,I,O")] Professor nameItem)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    context.Entry(nameItem).State = EntityState.Modified;
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(nameItem);
            }
            catch (Exception)
            {
                return Redirect("~/Professor/ErrorPage");
            }
        }

        // GET: NameItem/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Professor nameItem = context.Professor.Find(id);
            if (nameItem == null)
            {
                return HttpNotFound();
            }
            return View(nameItem);
        }

        // POST: Evaluation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Professor nameItem = context.Professor.Find(id);
            context.Professor.Remove(nameItem);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElJournal/Views/ProfItems/Create.cshtml
@model ElJournal.ProfessorsItem

@{
    ViewBag.Title = "Созданине зависимости педагог-предмет";
}

<style>
    .btn {
        margin-bottom: 10px;
    }

    .col {
        margin-bottom: 10px;
    }
</style>

<h2>Созданине зависимости педагог-предмет</h2>


<body class="d-flex h-100 text-bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Назначение педагогов</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @*@Html.LabelFor(model => model.ProfessorId, "ProfessorId", htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <div class="col-md-10">
                        @Html.DropDownList("ProfessorId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ProfessorId, "", new { @class = "text-danger" })
                        <p>Фамилия преподавателя</p>
                    </div>
                </div>

                <div class="form-group">
                    @*@Html.LabelFor(model => model.ItemId, "ItemId", htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <div class="col-md-10">
                        @Html.DropDownList("ItemId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
                        <p>Наименование предмета </p>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Создать зависимость" class="btn btn-light" />
                    </div>
                </div>
            </div>
        }
        <div>
            <button type="button" class="btn btn-light">@Html.ActionLink("Вернуться в список", "Index")</button>
        </div>
    </div>
</body>
        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

ElJournal/Views/ProfItems/Delete.cshtml
@model ElJournal.ProfessorsItem

@{
    ViewBag.Title = "Удаление";
}

<h2>Удаление студента</h2>

<style>
    .btn {
        margin-bottom: 10px;
    }

    .col {
        margin-bottom: 10px;
    }
</style>

<body class="d-flex h-100 text-bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <h3>Вы уверены, что хотите удалить данную запись?</h3>
        <div>
            <h4>Отменить данное действие будет невозможно.</h4>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Удалить безвозвратно" class="btn btn-danger" />
                    <button type="button" class="btn btn-light">@Html.ActionLink("Вернуться в список", "Index")</button>
                </div>
            }
        </div>
    </div>
</body>

ElJournal/Views/ProfItems/Edit.cshtml
@model ElJournal.ProfessorsItem

@{
    ViewBag.Title = "Edit";
}

<style>
    .btn {
        margin-bottom: 10px;
    }

    .col {
        margin-bottom: 10px;
    }
</style>

<h2>Редактироваить запись</h2>

<body class="d-flex h-100 text-bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>ProfessorsItem</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @*@Html.LabelFor(model => model.ProfessorId, "ProfessorId", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.DropDownList("ProfessorId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ProfessorId, "", new { @class = "text-danger" })
                    <p>Фамилия педагога</p>
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.ItemId, "ItemId", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.DropDownList("ItemId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
                    <p>Предмет, который он ведёт</p>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Сохранить изменения" class="btn btn-light" />
                </div>
            </div>
        </div>
        }

        <div>
            <button type="button" class="btn btn-light">@Html.ActionLink("Вернуться в список", "Index")</button>
        </div>
    </div>
    </body>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

ElJournal/Views/ProfItems/ErrorPage.cshtml
<style>

    .ErrorButton {
        color: black;
    }

    .btn {
        position: absolute;
    }

    .somediv {
        margin-top: 20px;
        display: flex;
        justify-content: center;
    }

    * {
        border: 0;
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }

    body {
        background: currentColor;
        display: flex;
        height: 100vh;
    }
    /* I. Containers */
    figure {
        font-size: 6px;
        margin: auto;
        padding: 4em 0;
        width: 64em;
    }

    figcaption {
        color: #fff;
        display: flex;
        align-content: space-between;
        flex-wrap: wrap;
        height: 17em;
    }

        figcaption span:before, .sad-mac:before {
            content: "";
            display: block;
            width: 1em;
            height: 1em;
            transform: translate(-1em,-1em);
        }

        figcaption span {
            display: inline-block;
            margin: 0 2em;
            width: 4em;
            height: 6em;
        }

    .sr-text {
        overflow: hidden;
        position: absolute;
        width: 0;
        height: 0;
    }
    /* II. Sprites */
    /* 1. Sad Mac */
    .sad-mac {
        background: #fff;
        margin: 0 auto 7em auto;
        width: 23em;
        height: 30em;
    }

        .sad-mac:before {
            box-shadow: 1em 1em, 23em 1em, 4em 3em, 5em 3em, 6em 3em, 7em 3em, 8em 3em, 9em 3em, 10em 3em, 11em 3em, 12em 3em, 13em 3em, 14em 3em, 15em 3em, 16em 3em, 17em 3em, 18em 3em, 19em 3em, 20em 3em, 3em 4em, 21em 4em, 3em 5em, 21em 5em, 3em 6em, 7em 6em, 9em 6em, 15em 6em, 17em 6em, 21em 6em, 3em 7em, 8em 7em, 16em 7em, 21em 7em, 3em 8em, 7em 8em, 9em 8em, 15em 8em, 17em 8em, 21em 8em, 3em 9em, 21em 9em, 3em 10em, 10em 10em, 13em 10em, 21em 10em, 3em 11em, 11em 11em, 12em 11em, 21em 11em, 3em 12em, 21em 12em, 3em 13em, 10em 13em, 11em 13em, 12em 13em, 13em 13em, 14em 13em, 21em 13em, 3em 14em, 9em 14em, 15em 14em, 16em 14em, 21em 14em, 3em 15em, 17em 15em, 21em 15em, 3em 16em, 21em 16em, 4em 17em, 5em 17em, 6em 17em, 7em 17em, 8em 17em, 9em 17em, 10em 17em, 11em 17em, 12em 17em, 13em 17em, 14em 17em, 15em 17em, 16em 17em, 17em 17em, 18em 17em, 19em 17em, 20em 17em, 3em 22em, 4em 22em, 5em 22em, 14em 22em, 15em 22em, 16em 22em, 17em 22em, 18em 22em, 19em 22em, 20em 22em, 1em 27em, 2em 27em, 3em 27em, 4em 27em, 5em 27em, 6em 27em, 7em 27em, 8em 27em, 9em 27em, 10em 27em, 11em 27em, 12em 27em, 13em 27em, 14em 27em, 15em 27em, 16em 27em, 17em 27em, 18em 27em, 19em 27em, 20em 27em, 21em 27em, 22em 27em, 23em 27em, 1em 28em, 23em 28em, 1em 29em, 23em 29em, 1em 30em, 23em 30em;
        }
    /* 2. Letters */
    ._0:before {
        box-shadow: 2em 1em, 3em 1em, 1em 2em, 1em 3em, 1em 4em, 1em 5em, 4em 2em, 4em 3em, 4em 4em, 4em 5em, 2em 4em, 3em 3em, 2em 6em, 3em 6em;
    }

    ._4:before {
        box-shadow: 1em 1em, 1em 2em, 1em 3em, 1em 4em, 4em 1em, 4em 2em, 4em 3em, 4em 4em, 2em 4em, 3em 4em, 4em 5em, 4em 6em;
    }

    .d:before {
        box-shadow: 1em 1em, 2em 1em, 3em 1em, 1em 2em, 4em 2em, 1em 3em, 4em 3em, 1em 4em, 4em 4em, 1em 5em, 4em 5em, 1em 6em, 2em 6em, 3em 6em;
    }

    .e:before {
        box-shadow: 1em 1em, 2em 1em, 3em 1em, 4em 1em, 1em 2em, 1em 3em, 2em 3em, 3em 3em, 1em 4em, 1em 5em, 1em 6em, 2em 6em, 3em 6em, 4em 6em;
    }

    .f:before {
        box-shadow: 1em 1em, 2em 1em, 3em 1em, 4em 1em, 1em 2em, 1em 3em, 2em 3em, 3em 3em, 1em 4em, 1em 5em, 1em 6em;
    }

    .n:before {
        box-shadow: 1em 1em, 1em 2em, 1em 3em, 1em 4em, 1em 5em, 1em 6em, 4em 1em, 4em 2em, 4em 3em, 4em 4em, 4em 5em, 4em 6em, 2em 3em, 3em 4em;
    }

    .o:before {
        box-shadow: 2em 1em, 3em 1em, 1em 2em, 1em 3em, 1em 4em, 1em 5em, 4em 2em, 4em 3em, 4em 4em, 4em 5em, 2em 6em, 3em 6em;
    }

    .r:before {
        box-shadow: 1em 1em, 2em 1em, 3em 1em, 4em 2em, 1em 2em, 1em 3em, 1em 4em, 2em 3em, 3em 3em, 1em 5em, 1em 6em, 4em 4em, 4em 5em, 4em 6em;
    }

    .t:before {
        box-shadow: 1em 1em, 2em 1em, 3em 1em, 2em 2em, 2em 3em, 2em 4em, 2em 5em, 2em 6em;
    }

    .u:before {
        box-shadow: 1em 1em, 1em 2em, 1em 3em, 1em 4em, 1em 5em, 4em 1em, 4em 2em, 4em 3em, 4em 4em, 4em 5em, 2em 6em, 3em 6em;
    }
    /* III. Responsiveness */
    /* This cannot be smoothly done using viewport units; sprite pixels will look divided when font size is a floating point. */
</style>

<figure>
    <div class="sad-mac"></div>
    <figcaption>
        <span class="sr-text">Error 404: Not Found</span>
        <span class="e"></span>
        <span class="r"></span>
        <span class="r"></span>
        <span class="o"></span>
        <span class="r"></span>
        <span class="_4"></span>
        <span class="_0"></span>
        <span class="_4"></span>
        <span class="n"></span>
        <span class="o"></span>
        <span class="t"></span>
        <span class="f"></span>
        <span class="o"></span>
        <span class="u"></span>
        <span class="n"></span>
        <span class="d"></span>
    </figcaption>
</figure>
<div class="somediv"><button type="button" class="btn btn-light m-lg-1 mb-1"><a class="ErrorButton" href="javascript: history.go(-1)">Вернуться на исходную страницу</a></button></div>

ElJournal/Views/ProfItems/Index.cshtml
@model IEnumerable<ElJournal.ProfessorsItem>
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Index";
}

<style>
    .newitems {
        color: white;
    }

    .nav-link {
        padding: 0;
        color: black;
    }

    .meh {
        color: white;
    }
</style>


<body class="d-flex h-100 text-center text-bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
            <div>
                <h3 class="float-md-start mb-0">Журнал информации</h3>
                <nav class="nav nav-masthead justify-content-center float-md-end">
                    @Html.Partial("_LoginPartial")
                    <button type="button" class="btn btn-light m-lg-1 mb-1">@Html.ActionLink("Домашняя страница", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</button>
                    <button type="button" class="btn btn-light m-lg-1 mb-1">@Html.ActionLink("Информация", "About", "Home", new { area = "" }, new { @class = "nav-link" })</button>
                    <button type="button" class="btn btn-light m-lg-1 mb-1"> @Html.ActionLink("Профиль", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage", @class = "nav-link" })</button>
                    @if (User.Identity.GetUserName() == "lulakushka@gmail.com")
                    {
                        <button type="button" class="btn btn-light m-lg-1 mb-1"> @Html.ActionLink("Лог действий", "Log", "Home", routeValues: null, htmlAttributes: new { title = "", @class = "nav-link" })</button>
                    }
                    else { }
                    <button type="button" class="btn btn-light m-lg-1 mb-1"><a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></button>
                </nav>
            </div>
        </header>

        <h2>Педагоги их дисциплины</h2>

        <p>
            <button type="button" class="btn btn-light m-lg-1 mb-1">@Html.ActionLink("Назначить педагога на дисциплину", "Create", new { area = "" }, new { @class = "nav-link" })</button>
            <button type="button" class="btn btn-light m-lg-1 mb-1">@Html.ActionLink("Вернуться к педагогам", "Index", "Professor", new { area = "" }, new { @class = "nav-link" })</button>
        </p>
        <table class="table">
            <tr>
                <th class="meh">
                    Фамилия педагога
                </th>
                <th class="meh">
                    Имя педагога
                </th>
                <th class="meh">
                    Дисциплина
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="meh">
                        @Html.DisplayFor(modelItem => item.Professor.F)
                    </td>
                    <td class="meh">
                        @Html.DisplayFor(modelItem => item.Professor.I)
                    </td>
                    <td class="meh">
                        @Html.DisplayFor(modelItem => item.Item.NameItem1)
                    </td>
                    <td class="meh">
                        <button type="button" class="btn btn-light">@Html.ActionLink("Редактировать", "Edit", new { id = item.Id })</button>
                        <button type="button" class="btn btn-light">@Html.ActionLink("Удалить", "Delete", new { id = item.Id })</button>
                    </td>
                </tr>
            }

        </table>
    </div>
</body>